### PR TITLE
Revamped the README and moved the log file

### PR DESCRIPTION
**Pull request by CleanMachine1**
I noticed that the download was a folder from November 15th 2020 

Instead I have replaced it with the necessary commands to install from github using git 

Hope this is alright

PS: This may break the update system, I haven't tested however I feel it will be fine due to the update.py file using raw.github anyway

### CODE REVIEW

**Comment by CleanMachine1** [comment]
Also moved log file into Commanderpi folder

**Comment by mobilegmYT** [comment]
@Jack477

**Comment by CleanMachine1** [comment]
@Jack477

**Comment by CleanMachine1** [comment]
@Jack477 Are you going to ever push or review this commit?

**Comment by CleanMachine1** [comment]
Why have you closed without any explanation?

**Comment by Jack477** [comment]
"Usage" is for installation and there was too many pull requests for change README.md file which is not important that much. `start.sh` I changed manually today.

**Comment by mobilegmYT** [comment]
> "Usage" is for installation and there was too many pull requests for change README.md file which is not important that much. `start.sh` I changed manually today.

Usage is usage, installation is installation, usage is not installation 😝 .

**Comment by Jack477** [comment]
> > "Usage" is for installation and there was too many pull requests for change README.md file which is not important that much. `start.sh` I changed manually today.
> 
> Usage is usage, installation is installation, usage is not installation 😝 .

I've used bad word to explain this 😝

**Comment by CleanMachine1** [comment]
Regardless, please explain why you are closing and let it be debated a little rather than closing without input. Thanks for your time regardless.

**Pull request closed without merging**
